// Mocks generated by Mockito 5.0.16 from annotations
// in rick_and_morty_client/test/src/features/characters_list/presentation/bloc/characters_list_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:either_dart/either.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rick_and_morty_client/src/core/domain/failures/failure.dart'
    as _i6;
import 'package:rick_and_morty_client/src/core/domain/repositories/character_repository.dart'
    as _i2;
import 'package:rick_and_morty_client/src/features/characters_list/domain/entities/characters_page.dart'
    as _i7;
import 'package:rick_and_morty_client/src/features/characters_list/domain/usecases/get_characters.dart'
    as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeCharacterRepository_0 extends _i1.Fake
    implements _i2.CharacterRepository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [GetCharacters].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCharacters extends _i1.Mock implements _i4.GetCharacters {
  MockGetCharacters() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CharacterRepository get repo => (super.noSuchMethod(
      Invocation.getter(#repo),
      returnValue: _FakeCharacterRepository_0()) as _i2.CharacterRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.CharactersPage>> call(int? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue:
                  Future<_i3.Either<_i6.Failure, _i7.CharactersPage>>.value(
                      _FakeEither_1<_i6.Failure, _i7.CharactersPage>()))
          as _i5.Future<_i3.Either<_i6.Failure, _i7.CharactersPage>>);
  @override
  String toString() => super.toString();
}
